# Site settings
title: TA LabBlog - technology and science at TheReviewIndex
description: "A blog for Text Analytics LAb."
url: "https://katejeong.github.io"
ogimage: "img/default-ogimage.png"
author:
  name: "Yoo"
  email: "yookyungjeong@gmail.com"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Order
header_pages:
  - about.md
  - research.md
  - project.md
  - teaching.md
  - service.md

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true
